### ISSUE TITLE
get_market_fundamental 관련 문의드립니다.

### ISSUE THREAD

**Issue by jin1-seo** [sharebook-kr/pykrx#106]
사용한 코드는 다음과 같습니다. (앞부분은 제외했습니다)

code_list = []
for data in data_rows: 
    codes = data['href'][-6:]
    code_list.append(codes)

for code in code_list:
    df = pd.DataFrame()
    df = stock.get_market_fundamental(std_day.strftime('%Y%m%d'), today.strftime('%Y%m%d'), code)
    if df.empty:
        pass
    else:
        print(code)
        print(df.head())
        print('------------------------------------')

여기서 code_list는 제가 따로 웹스크레이핑 해온 자료들이고, 날짜 값은 오늘과 1개월 이전 값으로 지정하도록 지정해 두었습니다. 여기서 출력할 경우 몇 번 까지는 잘 반복해서 동작하다가 다음과 같은 오류가 지속적으로 발생합니다.
Traceback (most recent call last):
  File "c:/myPackage/obvchart.py", line 28, in <module>
    df = stock.get_market_fundamental(std_day.strftime('%Y%m%d'), today.strftime('%Y%m%d'), code)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\pykrx\stock\api.py", line 659, in get_market_fundamental
    return get_market_fundamental_by_date(*args, **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\pykrx\stock\api.py", line 705, in get_market_fundamental_by_date
    df = krx.get_market_fundamental_by_date(fromdate, todate, ticker)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\pykrx\website\comm\util.py", line 7, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\pykrx\website\krx\market\wrap.py", line 212, in get_market_fundamental_by_date
    df = PER_PBR_배당수익률_개별().fetch(fromdate, todate, "ALL", isin)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\pykrx\website\krx\market\core.py", line 164, in fetch
    result = self.read(mktId=mktId, strtDd=strtDd, endDd=endDd, isuCd=isuCd)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\pykrx\website\krx\krxio.py", line 10, in read
    return resp.json()
  File "C:\UsersAppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
     raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

JSONDecodeError가 자꾸 중간 지점부터 발생하여 처음에는 네트워크 문제인 것 같아 타 네트워크 환경에서 실행시켜 보았는데, 같은 오류가 발생합니다.

**Comment by jin1-seo** [comment]
오늘 같은 코드를 실행시켰는데 작동이 잘 되네요. 긁어오는 개수가 너무 많아지면 간헐적으로 오류가 발생하는 것 같습니다.
