### ISSUE TITLE
get_market_ticker_list 관련 문의

### ISSUE THREAD

**Issue by leetan8909** [sharebook-kr/pykrx#145]
현재 4월 6일부터 해당 매서드를 호출하면 오류가 나고 있는데 따로 원인이 있나요?

**Comment by mr-yoo** [comment]
pykrx `1.0.41` 버전에서 정상동작하는데요. 

```
from pykrx import stock

tickers = stock.get_market_ticker_list()
print(tickers)
```
사용하고 계시는 `pykrx` 버전이 어떻게 되실까요?

**Comment by leetan8909** [comment]
1.41버전 쓰고 있고 아래와 위 코드 그대로 입력하면 아래처럼 오류가 나옵니다.


Traceback (most recent call last):
  File "C:\Users\PC\Desktop\LT\python-workspace\crawlingTest-workspace\test.py", line 3, in <module>
    tickers = stock.get_market_ticker_list()
  File "C:\Users\PC\Desktop\LT\python-workspace\crawlingTest-workspace\venv\lib\site-packages\pykrx\stock\stock_api.py", line 81, in get_market_ticker_list
    date = get_nearest_business_day_in_a_week()
  File "C:\Users\PC\Desktop\LT\python-workspace\crawlingTest-workspace\venv\lib\site-packages\pykrx\stock\stock_api.py", line 67, in get_nearest_business_day_in_a_week
    return krx.get_nearest_business_day_in_a_week(date, prev)
  File "C:\Users\PC\Desktop\LT\python-workspace\crawlingTest-workspace\venv\lib\site-packages\pykrx\website\krx\__init__.py", line 36, in get_nearest_business_day_in_a_week
    df = get_index_ohlcv_by_date(prev, curr, "1001")
  File "C:\Users\PC\Desktop\LT\python-workspace\crawlingTest-workspace\venv\lib\site-packages\pykrx\website\comm\util.py", line 8, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\PC\Desktop\LT\python-workspace\crawlingTest-workspace\venv\lib\site-packages\pykrx\website\krx\market\wrap.py", line 819, in get_index_ohlcv_by_date
    df = 개별지수시세().fetch(ticker[1:], ticker[0], fromdate, todate)
  File "C:\Users\PC\Desktop\LT\python-workspace\crawlingTest-workspace\venv\lib\site-packages\pykrx\website\krx\market\core.py", line 765, in fetch
    result = self.read(indIdx2=ticker, indIdx=group_id, strtDd=fromdate,
  File "C:\Users\PC\Desktop\LT\python-workspace\crawlingTest-workspace\venv\lib\site-packages\pykrx\website\krx\krxio.py", line 24, in read
    return resp.json()
  File "C:\Users\PC\Desktop\LT\python-workspace\crawlingTest-workspace\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 16 column 3 (char 36)

Process finished with exit code 1

**Comment by mr-yoo** [comment]
환경이 꼬인것 같은데 가상환경에서 테스트해 보시겠어요? 윈도우 아나콘다 프롬프트에서 다음 명령을 실행하면 됩니다.

```
$ python -m venv venv
$ venv\Scripts\activate
$ pip install pykrx
```

그리고 이어서 python을 실행하고 코드를 입력해 보세요.

```
$ python
```
