### ISSUE TITLE
get_index_fundamental 함수 정보 누락

### ISSUE THREAD

**Issue by wonseok0109** [sharebook-kr/pykrx#179]
안녕하세요 pykrx를 너무 잘 사용해오고 있던 유저입니다.

그런데 최근 get_index_fundamental 함수가 작동하지 않는 것 같아서 문의드립니다.

print(stock.get_index_fundamental("20240422", "20240426", "1001"))
>>>
Empty DataFrame
Columns: []
Index: []

이렇게 나오고 있는데, 날짜를 바꾸어도 마찬가지 입니다. 
혹시 더이상 get_index_fundamental 함수를 지원하지 않는건지 문의드립니다. 감사합니다.

**Comment by hawkingPower** [comment]
저도 해보니 잘 안되네요. get_index_fundamental 확인 부탁 드립니다.

**Comment by elcsong** [comment]
맞아요 저도 다음과 같이 실행해봤는데 아무런 데이터를 반환하지 않습니다.

from pykrx import stock

stock.get_index_fundamental('20240501','20240503','1001')

___

**Comment by artiveloper** [comment]
4월 29일부터 에러가 발생했습니다.

`Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pykrx/website/comm/util.py", line 8, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pykrx/website/krx/market/wrap.py", line 1010, in get_index_fundamental_by_ticker
    df = df[['IDX_NM', 'CLSPRC_IDX', 'FLUC_RT', 'WT_PER', 'FWD_PER',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/usr/local/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6179, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['FWD_PER'] not in index"
`

**Comment by hyunsikhwang** [comment]
저도 동일한 이슈를 겪고 있습니다

**Comment by mr-yoo** [comment]
데이터 레이아웃이 바뀌었네요. 선행PER 데이터가 서버에서 사라져서 관련 코드를 수정(e8be1e79)했습니다. 모듈 업데이트 후 확인해주세요.
