### ISSUE TITLE
python 3.5에서 import 에러가 나네요

### ISSUE THREAD

**Issue by luke0705** [sharebook-kr/pykrx#51]
안녕하세요.
덕분에 잘 사용하고 있었습니다.
근데 이번 KRX 사이트 리뉴얼로 새로운 버전을다운받아 사용하려했는데
from pykrx import stock 명령어에서 아래와 같은 에러가 나옵니다.
python3.5 환경에서의 문제인것 같은데 이전처럼 낮은 버전의 python에서도 사용할 수 있었으면 좋겠습니다.

Traceback (most recent call last):
  File "/volume1/DART/python/getStockCode.py", line 5, in <module>
    from pykrx import stock
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/pykrx/stock/__init__.py", line 1, in <module>
    from .api import *
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/pykrx/stock/api.py", line 20
    print(f"market 옵션이 올바르지 않습니다." )
                                 ^
SyntaxError: invalid syntax

**Comment by mr-yoo** [comment]
파이썬 3.5는 `2015`년도에 release 된 오래전 버전입니다. 위 에러는 파이썬 3.5가 `f-string`을 지원하지 않아 문자열 출력에서 에러가 발생하는 것으로 보입니다. `f-string`을 제거하더라도 다른 모듈 dependency 문제가 발생할 수 있습니다. 특별한 이유가 없다면 가상환경이나 파이썬 업그레이드를 하시는게 어떨까요?
