### ISSUE TITLE
exception, get_market_ticker_name

### ISSUE THREAD

**Issue by InssaGwajang** [sharebook-kr/pykrx#56]
한달 전 쯔음에는 문제가 없었던 동작인데, get_market_ticker_name 에서 문제가 발생합니다.
 가장 최근 버전으로 업데이트를 해도 동일한 문제가 발생하는데, 확인 부탁드립니다.

 : 재현 가능한 코드

from pykrx import stock as krx
for ticker in krx.get_market_ticker_list(date="20101230", market="KOSPI"):
    krx.get_market_ticker_name(ticker)

 : 에러 메시지

ERROR:root:'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pykrx/website/comm/util.py", line 7, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pykrx/website/krx/market/ticker.py", line 53, in get_stock_name
    return s['종목']
TypeError: 'NoneType' object is not subscriptable

**Comment by mr-yoo** [comment]
최근 10일전 KRX 웹페이지가 개편됨에 따라 API 내부가 크게 변경됐습니다. 
이에 따라 스크래핑이 제대로 이뤄지지 않는 것 같습니다. 

우선 최신 버전이 맞는지 확인이 필요합니다. 
```python
import pykrx
print(pykrx.__version__)
```
```
1.0.7
```

최신 버전이 아니라면 모듈 업데이트 부탁드려요.
`pip install -U pykrx`

보통 virtualenv 경로 혹은 모듈 버전 문제에서 비슷한 문제가 많이 발생합니다.

----

웹에서 (깨끗한 환경)에서 테스트 했을 때 다음과 같이 올바른 결과가 출력 됩니다.
https://repl.it/@Jonghunyoo/pykrxissue56#main.py  (웹이라 실행 속도는 느립니다.)
![image](https://user-images.githubusercontent.com/29349211/106539524-83982d00-6541-11eb-8cb3-8ec0c9fe3e53.png)

**Comment by InssaGwajang** [comment]
import pykrx

print(pykrx.__version__)

from pykrx import stock as krx

for ticker in krx.get_market_ticker_list(date="20071228", market="KOSPI"):
    if not isinstance(name := krx.get_market_ticker_name(ticker), str):
        print(ticker, name)

위의 코드로 한번만 더 확인해주시겠어요?
저는 아래와 같이 출력됩니다.

1.0.7
001047 Empty DataFrame
Columns: []
Index: []
001049 Empty DataFrame
Columns: []
Index: []
097957 Empty DataFrame
Columns: []
Index: []
097959 Empty DataFrame
Columns: []
Index: []
004137 Empty DataFrame
Columns: []
Index: []
001687 Empty DataFrame
Columns: []
Index: []
084697 Empty DataFrame
Columns: []
Index: []
002027 Empty DataFrame
Columns: []
Index: []

**Comment by mr-yoo** [comment]
@InssaGwajang 
저야 얼마든지 테스트해 볼 수 있습니다. 

----

제 로컬이랑 온라인에서 제대로 출력 되는 것으로 보아 두 가지 문제가 있을 수 있습니다.
1) 모듈 문제 
2) 환경 문제 

두 가지를 한 번에 해결하기 위해 가상 환경에서 새롭게 환결 설치 후 테스트 해볼 것을 추천 드립니다. 
저는 파이썬 3.8과 3.9에서 확인해 봤습니다. 

----

모듈 dependency로 인한 문제라면 디버깅을 해주시면 좋구요..


참고로 다음 로그 옵션을 켜면 Empty DataFrame이 출력되는 원인을 간략히 볼 수는 있습니다.
```python
import logging
logging.basicConfig(level=logging.INFO)
```

**Comment by InssaGwajang** [comment]
로깅을 켜보니, 다음과 같은 메시지가 추가적으로 나옵니다.

```
INFO:root:'NoneType' object is not subscriptable
001047 Empty DataFrame
Columns: []
Index: []
```

알려주신 pip 정보들을 토대로, 설치되어 있는 package 들을 모두 버전을 맞추어보았으나, 동일한 문제가 나오네요.
저는 MacOS BigSur, Python 3.8.3 64-bit 입니다.

상폐종목 중에 103130 웅진에너지 와 같은 종목은 나오는데, 왜 우량주 상폐종목 몇가지가 문제를 일으키는지..

제가 디버깅을 좀 더 진행해봐야겠네요.
신경 써주셔서 감사합니다.
해결하게 되면 여기에 추가적으로 코멘트를 남겨두겠습니다.

**Comment by mr-yoo** [comment]
처음에 전달해 주신 코스피 종목 조회 코드는 제 환경에서 정상동작합니다.
```python
for ticker in get_market_ticker_list(date="20101230", market="KOSPI"):
        print(ticker, get_market_ticker_name(ticker))
```

위 에러를 참고해서 실행한 코드는 저도 동일한 문제가 발생합니다. 
`print(get_market_ticker_name("001047"))`
```text
Empty DataFrame
Columns: []
Index: []
```

**Comment by mr-yoo** [comment]
두 번째 언급하신 코드를 보니 날짜가 변경돼 있네요. 
```python
for ticker in get_market_ticker_list(date="20071228", market="KOSPI"):
        print(ticker, get_market_ticker_name(ticker))
```

날짜를 `20071228`로 변경하니 중간 중간 empty data frame 이 출력됩니다. 
상장 폐지 종목의 티커 처리가 빠진게 있나 봅니다.

**Comment by InssaGwajang** [comment]
issue reporting 을 좀 더 잘 했어야 했는데, 혼선이 생긴것 같아 죄송스럽네요.
성향상 웬만한건 구현해서 사용하는데,
pykrx 기능들은 거래소 사정이 따라 바뀔 수 있는 것들이 많아 감사하는 마음으로 사용하고 있습니다.

**Comment by mr-yoo** [comment]
아녜요. 오히려 문제 reporting을 해주셔서 감사합니다. 
제가 잘 읽었으면 될 일이죠. 

상장 폐지 정보를 얻어와서 어떻게 합칠지 고민 해보겠습니다.

**Comment by mr-yoo** [comment]
`20071228` 데이터에서 다음 상장 폐지된 종목의 정보가 웹페이지에 존재하지 않아 KRX 웹페이지에 문의를 남겨 뒀습니다. 
```
001047
001049
097957
097959
004137
001687
084697
002027
```

**Comment by mr-yoo** [comment]
우선 아래와 같은 답변을 받았습니다. 

> 제목 : [답변] 누락된 상장폐지 종목 정보
\
안녕하세요, 한국거래소 정보사업부에서 답변드립니다.           
먼저 한국거래소 정보데이터시스템을  이용해주셔서 감사드립니다.          
\
[20037] 화면에서 일부 상장폐지종목이  검색되지 않는 부분에 대해 문의주셨습니다.  해당 부분에 대해 확인결과, 상장폐지사유가 '종류변경'인   경우에 일부 우선주 종목에 대해  확인이 되지 않는것을 확인하였습니다.          
\
추후 홈페이지 개편작업시 추가하여  반영할 예정입니다.           
감사합니다.                                                                      

웹 서버에서 정보를 얻기 어려우니 우선은 티커와 이름을 DataFrame으로 반환하는 함수를 하나 만들까 합니다. 
```python
>> get_market_tickers(date="20071228", market="KOSPI")
```
