### ISSUE TITLE
exception, get_market_cap_by_ticker

### ISSUE THREAD

**Issue by InssaGwajang** [sharebook-kr/pykrx#57]
문제라고 봐야 할지는 모르겠습니다.

휴장일에 해당하는 market cap 을 요청하면, exception 이 발생합니다.
fetch 된 값이 '-' 로 채워져 있어서,
df = df.astype(np.int64) (pykrx/website\krx\market\wrap.py 151 line 에서 exception 발생합니다.

제가 가지고 있던 휴장일 데이터에 문제가 있어서 휴장일로 요청했습니다.

```
import datetime, logging
from pykrx import stock as krx

krx_caps = krx.get_market_cap_by_ticker("20070501")
```

```
Traceback (most recent call last):
  File "/Users/taehee.won/dev.project/python/python-inssa-IGSA/p.py", line 10, in <module>
    krx_caps = krx.get_market_cap_by_ticker(target)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pykrx/stock/api.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pykrx/stock/api.py", line 295, in get_market_cap_by_ticker
    return krx.get_market_cap_by_ticker(date, market, acending)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pykrx/website/comm/util.py", line 7, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pykrx/website/krx/market/wrap.py", line 151, in get_market_cap_by_ticker
    df = df.astype(np.int64)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/generic.py", line 5874, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 631, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 427, in apply
    applied = getattr(b, f)(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 673, in astype
    values = astype_nansafe(vals1d, dtype, copy=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/dtypes/cast.py", line 1074, in astype_nansafe
    return lib.astype_intsafe(arr.ravel(), dtype).reshape(arr.shape)
  File "pandas/_libs/lib.pyx", line 619, in pandas._libs.lib.astype_intsafe
ValueError: invalid literal for int() with base 10: '-'
```

**Comment by mr-yoo** [comment]
휴일일 경우 인접한 영업일로 재조회 하도록 수정했습니다.
- https://github.com/sharebook-kr/pykrx/commit/f0c5c0fb7a5d3a70fc90c70dda1862d31f9243ec#r46686456

또한 함수의 휴일 처리 테스트 로직이 빠져 있어서 추가했습니다. 
참고로 코드는 merge 했고 모듈은 추후 업데이트할 예정입니다.

**Comment by mr-yoo** [comment]
```python
from pykrx import stock as krx

krx_caps = krx.get_market_cap_by_ticker("20070501")
print(krx_caps)
```

```text
The date you entered 20070501 seems to be a holiday. PYKRX changes the date parameter to 20070430 toquery the requested information.
             종가       시가총액    거래량      거래대금  상장주식수
티커                                                               
005930   574000  84549819438000   377020  216199846000  147299337
005490   393500  34308019572500  1056921  416035898000   87186835
060000    83500  28087656186000   668993   55722772300  336379116
015760    37950  24347494670400   788180   29976294250  641567712
```
